Transportation

Diesel Transport Cost Per Truck

In [ ]:

import pandas as pd

#Medium truck: Class 6
#Large truck: Class 8

#Cost per km
cost_per_km_Class6 = 0.15 + 0.09+ 0.028 + 0.24375
cost_per_km_Class8 = 0.18 + 0.1625 + 0.052 + 0.4375
distance_km = 2369

#Truck capacities
capacity_Class6 = 50
capacity_Class8 = 100

#Volumes to shipped based on the volumes of prepacks 
volumes = [36.350505, 36.648375]

#Fuel prices and efficiencies
fuel_price = 1.56  # per liter based on the average of our locations
fuel_consumption_Class6 = 0.18 # liter per km
fuel_consumption_Class8 = 0.3 

def calculate_combination_costs(volume):
    best_cost = float('inf')
    best_combination = None

    for num_Class8 in range(int(volume // capacity_Class8) + 2):
        for num_Class6 in range(int(volume // capacity_Class6) + 2):
            total_capacity = num_Class8 * capacity_Class8 + num_Class6 * capacity_Class6 
            if total_capacity >= volume:

                # Base cost
                base_cost_Class6 = num_Class6 * cost_per_km_Class6 * distance_km
                base_cost_Class8 = num_Class8 * cost_per_km_Class8 * distance_km

                # Fuel cost
                fuel_cost_class6 = distance_km * fuel_price * fuel_consumption_Class6* num_Class6
                fuel_cost_class8 = distance_km * fuel_price * fuel_consumption_Class8 * num_Class8
                
                # Interim cost
                interim_cost =  base_cost_Class6 + base_cost_Class8  + fuel_cost_class6 + fuel_cost_class8 

                # Penalty cost
                penalty_rate = 0.2 * (interim_cost / total_capacity)
                overcapacity_penalty = (total_capacity - volume) * penalty_rate

                # Total cost
                total_cost = interim_cost + overcapacity_penalty

                if total_cost < best_cost:
                    best_cost = total_cost
                    best_combination = ( num_Class6, num_Class8, total_cost)

    return best_combination

#Applies the function to each shipment volume in the list
combination_costs = [calculate_combination_costs(volume) for volume in volumes]
combination_costs = pd.DataFrame(combination_costs, columns=[ 'Class6', 'Class8', 'Total Cost'])
combination_costs

   Class6  Class8   Total Cost
0       1       0  1980.061439
1       1       0  1977.824375

Electric Transport Cost Per Truck

In [ ]:
import pandas as pd

#ElectricMedium truck: EClass6
#ElectricLarge truck: EClass 8

#Cost per km
cost_per_km_EClass6 = 0.09 + 0.125 + 0.04 + 0.24375 
cost_per_km_EClass8 = 0.1 + 0.35 + 0.112 + 0.4375
distance_km = 2369

#Truck capacities
capacity_EClass6 = 30
capacity_EClass8 = 65

#Volumes to shipped based on the volumes of prepacks 
volumes = [36.350505, 36.648375]

#Charging cost
charge_price_km = 0.079 # cost per km fpr fast charging
charge_consumption_EClass6 = 0.88 #kWh per km
charge_consumption_EClass8 = 1.242 

#Wages per hour
wage_EClass6 = 19.5
wage_EClass8 = 35

#Battery charge hours and range
range_EClass6 = 300
range_EClass8 = 500
battery_EClass6 = 5.3
battery_EClass8 = 12.42

def calculate_combination_costs(volume, distance_km):
    best_cost = float('inf')
    best_combination = None

    for num_EClass8 in range(int(volume // capacity_EClass8) + 2):
        for num_EClass6 in range(int(volume // capacity_EClass8) + 2):
                total_capacity = num_EClass8 * capacity_EClass8 + num_EClass6 * capacity_EClass6 
                if total_capacity >= volume:
                    # Base cost
                    base_cost_EClass6 = num_EClass6 * cost_per_km_EClass6 * distance_km
                    base_cost_EClass8 = num_EClass8 * cost_per_km_EClass8 * distance_km
                    
                    # Charge cost
                    charge_cost_EClass6 = distance_km * charge_price_km / charge_consumption_EClass6 * num_EClass6
                    charge_cost_EClass8 = distance_km * charge_price_km / charge_consumption_EClass8 *  num_EClass8

                    # Wait cost
                    wait_cost_EClass6 = wage_EClass6 * battery_EClass6 * distance_km / range_EClass6
                    wait_cost_EClass8 = wage_EClass8 * battery_EClass8 * distance_km / range_EClass8
                    
                    # Interim cost
                    interim_cost = (base_cost_EClass6 + base_cost_EClass8 +  charge_cost_EClass6 + charge_cost_EClass8 +  wait_cost_EClass6 + wait_cost_EClass8)

                    # Penalty cost
                    penalty_rate = 0.2 * (interim_cost / total_capacity)
                    overcapacity_penalty = (total_capacity - volume) * penalty_rate

                    # Total cost
                    total_cost = interim_cost + overcapacity_penalty

                    if total_cost < best_cost:
                        best_cost = total_cost
                        best_combination = (num_EClass6, num_EClass8, total_cost)

    return best_combination          

#Applies the function to each shipment volume in the list
combination_costs = [calculate_combination_costs(volume, distance_km) for volume in volumes]
combination_costs = pd.DataFrame(combination_costs, columns=['EClass6', 'EClass8', 'Total Cost'])
combination_costs

   EClass6  EClass8   Total Cost
0        0        1  5869.743506
1        0        1  5864.799570

Diesel transport cluster costs

In [ ]:

import pandas as pd

#Medium truck: Class 6
#Large truck: Class 8

#Cost per km
cost_per_km_Class6 = 0.15 + 0.09+ 0.028 + 0.24375
cost_per_km_Class8 = 0.18 + 0.1625 + 0.052 + 0.4375

#Distance Clusters Estimated
distance_Am_Pa_Br = 500
distance_Be_Co = 450
distance_He_St = 500
distance_to_Ma = 600
distance_to_Ro = 2500
distance_to_Am_Pa_Br = 1750
distance_to_Be_Co = 2850
distance_to_He_St = 3750

#Truck capacities
capacity_Class6 = 50
capacity_Class8 = 100

#Volumes to shipped based on the volumes of prepacks (this is from other group)
shipments = [(36.350505*3, distance_Am_Pa_Br),(36.350505*2, distance_Be_Co),(36.350505*2, distance_He_St),(36.350505, distance_to_Ma),(36.350505, distance_to_Ro),(36.350505*3, distance_to_Am_Pa_Br),(36.350505*2, distance_to_Be_Co),(36.350505*2, distance_to_He_St)]

shipment_names = [
    "Am_Pa_Br", "Be_Co", "He_St", "To_Ma", "To_Ro", "To_Am_Pa_Br", "To_Be_Co", 
    "To_He_St"
]

#Fuel prices and efficiencies
fuel_price = 1.56  # per liter based on the average of our locations
fuel_consumption_Class6 = 0.18# liter per km
fuel_consumption_Class8 = 0.3 

def calculate_combination_costs(volume_and_dist):
    volume, distance_km = volume_and_dist
    best_cost = float('inf')
    best_combination = None

    for num_Class8 in range(int(volume // capacity_Class8) + 2):
        for num_Class6 in range(int(volume // capacity_Class6) + 2):
            total_capacity = num_Class8 * capacity_Class8 + num_Class6 * capacity_Class6 
            if total_capacity >= volume:

                # Base cost
                base_cost_Class6 = num_Class6 * cost_per_km_Class6 * distance_km
                base_cost_Class8 = num_Class8 * cost_per_km_Class8 * distance_km

                # Fuel cost
                fuel_cost_class6 = distance_km * fuel_price * fuel_consumption_Class6* num_Class6
                fuel_cost_class8 = distance_km * fuel_price * fuel_consumption_Class8 * num_Class8
                
                # Interim cost
                interim_cost =  base_cost_Class6 + base_cost_Class8  + fuel_cost_class6 + fuel_cost_class8 

                # Penalty cost
                penalty_rate = 0.2 * (interim_cost / total_capacity)
                overcapacity_penalty = (total_capacity - volume) * penalty_rate

                # Total cost
                total_cost = interim_cost + overcapacity_penalty

                if total_cost < best_cost:
                    best_cost = total_cost
                    best_combination = ( num_Class6, num_Class8, total_cost)

    return best_combination

#Applies the function to each shipment volume in the list
combination_costs = [(name, *calculate_combination_costs((volume, dist))) for name, (volume, dist) in zip(shipment_names,shipments)]
combination_costs = pd.DataFrame(combination_costs, columns=[ 'Delivery route','Class6', 'Class8', 'Total Cost'])
combination_costs

  Delivery route  Class6  Class8   Total Cost
0       Am_Pa_Br       1       1  1103.399502
1          Be_Co       0       1   616.939818
2          He_St       0       1   685.488687
3          To_Ma       1       0   501.492977
4          To_Ro       1       0  2089.554073
5    To_Am_Pa_Br       1       1  3861.898255
6       To_Be_Co       0       1  3907.285516
7       To_He_St       0       1  5141.165152

Electric transport cluster cost

In [ ]:
import pandas as pd

#ElectricMedium truck: EClass6
#ElectricLarge truck: EClass 8

#Cost per km
cost_per_km_EClass6 = 0.09 + 0.125 + 0.04 + 0.24375 
cost_per_km_EClass8 = 0.1 + 0.35 + 0.112 + 0.4375

#Distance Clusters Estimated
distance_Am_Pa_Br = 500
distance_Be_Co = 450
distance_He_St = 500
distance_to_Ma = 600
distance_to_Ro = 2500
distance_to_Am_Pa_Br = 1750
distance_to_Be_Co = 2850
distance_to_He_St = 3750

#Truck capacities
capacity_EClass6 = 30
capacity_EClass8 = 65

#Volumes to shipped based on the volumes of prepacks (this is from other group)
shipments = [(36.350505*3, distance_Am_Pa_Br),(36.350505*2, distance_Be_Co),(36.350505*2, distance_He_St),(36.350505, distance_to_Ma),(36.350505, distance_to_Ro),(36.350505*3, distance_to_Am_Pa_Br),(36.350505*2, distance_to_Be_Co),(36.350505*2, distance_to_He_St), (38.20302*3, distance_Am_Pa_Br),(38.20302*2, distance_Be_Co),(38.20302*2, distance_He_St),(38.20302, distance_to_Ma),(38.20302, distance_to_Ro),(38.20302*3, distance_to_Am_Pa_Br),(38.20302*2, distance_to_Be_Co),(38.20302*2, distance_to_He_St)]


#Charging cost
charge_price_km = 0.079 # cost per km fpr fast charging
charge_consumption_EClass6 = 0.88 #kWh per km
charge_consumption_EClass8 = 1.242 

#Wages per hour
wage_EClass6 = 19.5
wage_EClass8 = 35

#Battery charge hours and range
range_EClass6 = 300
range_EClass8 = 500
battery_EClass6 = 5.3
battery_EClass8 = 12.42

def calculate_combination_costs(volume_and_dist):
    volume, distance_km = volume_and_dist
    best_cost = float('inf')
    best_combination = None
    
    for num_EClass8 in range(int(volume // capacity_EClass8) + 2):
        for num_EClass6 in range(int(volume // capacity_EClass8) + 2):
                total_capacity = num_EClass8 * capacity_EClass8 + num_EClass6 * capacity_EClass6 
                if total_capacity >= volume:
                    # Base cost
                    base_cost_EClass6 = num_EClass6 * cost_per_km_EClass6 * distance_km
                    base_cost_EClass8 = num_EClass8 * cost_per_km_EClass8 * distance_km
                    
                    # Charge cost
                    charge_cost_EClass6 = distance_km * charge_price_km / charge_consumption_EClass6 * num_EClass6
                    charge_cost_EClass8 = distance_km * charge_price_km / charge_consumption_EClass8 *  num_EClass8

                    # Wait cost
                    wait_cost_EClass6 = wage_EClass6 * battery_EClass6 * distance_km / range_EClass6
                    wait_cost_EClass8 = wage_EClass8 * battery_EClass8 * distance_km / range_EClass8
                    
                    # Interim cost
                    interim_cost = (base_cost_EClass6 + base_cost_EClass8 +  charge_cost_EClass6 + charge_cost_EClass8 +  wait_cost_EClass6 + wait_cost_EClass8)

                    # Penalty cost
                    penalty_rate = 0.2 * (interim_cost / total_capacity)
                    overcapacity_penalty = (total_capacity - volume) * penalty_rate

                    # Total cost
                    total_cost = interim_cost + overcapacity_penalty

                    if total_cost < best_cost:
                        best_cost = total_cost
                        best_combination = (num_EClass6, num_EClass8, total_cost)

    return best_combination          

#Applies the function to each shipment volume in the list
combination_costs = [(name, *calculate_combination_costs((volume, dist))) for name, (volume, dist) in zip(shipment_names,shipments)]
combination_costs = pd.DataFrame(combination_costs, columns=[ 'Delivery route','Class6', 'Class8', 'Total Cost'])
combination_costs

  Delivery route  Class6  Class8    Total Cost
0       Am_Pa_Br       0       2   1723.880417
1          Be_Co       1       1   1350.023762
2          He_St       1       1   1500.026402
3          To_Ma       0       1   1486.638288
4          To_Ro       0       1   6194.326199
5    To_Am_Pa_Br       0       2   6033.581461
6       To_Be_Co       1       1   8550.150490
7       To_He_St       1       1  11250.198013